version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: springsecuritydb
      POSTGRES_USER: spring
      POSTGRES_PASSWORD: spring
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  app:
    image: ashutoshpandey/springsecurity:latest
    ports:
      - "8080:8080"
